version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: integratedexperts/circleci2-builder
        environment:
          COMPOSER_ALLOW_SUPERUSER: 1
          COMPOSE_PROJECT_NAME: govcms
          DEPLOY_BRANCH: 7.x-3.x
    steps:
      - checkout
      - run:
          name: Push Docker images to Dockerhub
          command: |
            if [ "${DEPLOY_ANY_BRANCH}" != "" ] || [ "${CIRCLE_BRANCH}" == "${DEPLOY_BRANCH}" ] || [ -z ${CIRCLE_TAG} ]; then
              echo "IMAGE_VERSION_TAG=$CIRCLE_TAG">>.env
              echo "deploying!"
            else
              echo "Skipping deployment"
            fi
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
